version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    container_name: blog-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: blog_db
    volumes:
      - blog-postgres-data:/var/lib/postgresql/data

volumes:
  blog-postgres-data:
